// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJbymWsqRGnZC8uMWYy0YjyULAEAmdZk',
    appId: '1:966677763899:web:b7fac1353fccfc0b15491e',
    messagingSenderId: '966677763899',
    projectId: 'teste1-ed9c8',
    authDomain: 'teste1-ed9c8.firebaseapp.com',
    databaseURL: 'https://teste1-ed9c8-default-rtdb.firebaseio.com',
    storageBucket: 'teste1-ed9c8.firebasestorage.app',
    measurementId: 'G-FPT8RXVHFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcByfL0TH5rk76jDhONd-GOe-_jJ6dUo8',
    appId: '1:966677763899:android:c4d6debe7efb77a915491e',
    messagingSenderId: '966677763899',
    projectId: 'teste1-ed9c8',
    databaseURL: 'https://teste1-ed9c8-default-rtdb.firebaseio.com',
    storageBucket: 'teste1-ed9c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLSZzr_-08J3c5D81wzLe6qJfq50PgahE',
    appId: '1:966677763899:ios:7690b9f3b74a1ed415491e',
    messagingSenderId: '966677763899',
    projectId: 'teste1-ed9c8',
    databaseURL: 'https://teste1-ed9c8-default-rtdb.firebaseio.com',
    storageBucket: 'teste1-ed9c8.firebasestorage.app',
    iosBundleId: 'com.example.brainmonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLSZzr_-08J3c5D81wzLe6qJfq50PgahE',
    appId: '1:966677763899:ios:7690b9f3b74a1ed415491e',
    messagingSenderId: '966677763899',
    projectId: 'teste1-ed9c8',
    databaseURL: 'https://teste1-ed9c8-default-rtdb.firebaseio.com',
    storageBucket: 'teste1-ed9c8.firebasestorage.app',
    iosBundleId: 'com.example.brainmonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEdIg8dt8cDGpraZ5Sz42K1eMlSr9hP4',
    appId: '1:966677763899:web:050c9ac35a84348d15491e',
    messagingSenderId: '966677763899',
    projectId: 'teste1-ed9c8',
    authDomain: 'teste1-ed9c8.firebaseapp.com',
    databaseURL: 'https://teste1-ed9c8-default-rtdb.firebaseio.com',
    storageBucket: 'teste1-ed9c8.firebasestorage.app',
    measurementId: 'G-PZ3SSSPHQ1',
  );
}
